### ISSUE TITLE
Is it possible to cache docker images in github actions? 

### ISSUE THREAD

**Issue by takashioya** [cvpaperchallenge/Ascender#68]
## Why

With the current setup, the docker image needs to be rebuilt every time there is a push or pull request, resulting in very long waiting times.

## Definition of Done

We need to update `.github/workflows/lint-and-test.yaml` to support caching of docker images.

## How

[This repository](https://github.com/marketplace/actions/docker-layer-caching) may be helpful, but it may be not maintained now 😢 .

**Comment by gatheluck** [comment]
@takashioya Thank you for raising this issue, and sorry for my late reply. I'm working on this ticket now. We will raise a PR within a few days. Thank you for patience!

**Comment by gatheluck** [comment]
@takashioya Sorry, this is taking more time than I expected first. But I'm actively working on this. So please wait a little more.

**Comment by gatheluck** [comment]
https://github.com/cvpaperchallenge/Ascender/pull/71
@takashioya I finalized PR. Now this PR is under review process. If you have time, I would appreciate your review.

**Comment by gatheluck** [comment]
@takashioya Thank you for your patience! Now #71 is merged, this feature will be available by next release. We will release 0.1.2 in this week.

**Comment by gatheluck** [comment]
@takashioya We just released 0.1.2. Now caching is introduced in CI job!

**Comment by takashioya** [comment]
That is really kind of you, and I apologize for not having the time to review the PR. This feature is really helpful because docker images tend to be very large in machine learning projects and take a long time to build, thank you!
